How many numbers are smaller than the current number
Phillie19/Tasks pull request #2
Opened 2020-03-11 09:37 UTC by Phillie19

В этой ветке я выложил два решения задачи **№1365 "How many numbers are smaller than the current number"** взятой с **Leetcode.com**. Одно работает побыстрее, другое помедленнее.
Суть задачи состоит в том, что дан массив чисел **nums**, необходимо найти сколько элементов из **nums**  строго меньше каждого **nums[i]**.

Разберем первое решение, код которого вы можете найти в прикрепленных файлах под именем "Solution #1.cpp".

**Алгоритм:**

1. Записать исходный массив чисел в **multiset**, тем самым отсортировав его;
2. Пройти циклом по **nums** и найти "индекс" **nums[i]** в **multiset**. "Индекс" это число, выражаемое через расстояние/_distance( , )_ от указателя на начало/_.begin()_ **multiset** до указателя на первый найденный элемент/_.lower_bound()_ равный **nums[i]**;
3. Записать полученные "индексы" в новый вектор-ответ и вывести его на экран.

**Результат:** Данное решение было выполнено за 28 мс и задействовало 9.6 МБ памяти. Время выполнения оказалось быстрее, чем у 43,01% всех принятых решений других участников.

Во втором решении "Solution #2.cpp" я использовал сортировку подсчетом.

**Алгоритм:**

1. Создать нулевой "сортировочный" вектор **sort[101]** размером в 101 элемент (по условию **nums[i]** могут принимать значения от 0 до 100).
2. Пройти циклом по **nums**, посчитать и записать в соответствующую ячейку **sort[nums[i]]** сколько раз в **nums** встречается **nums[i]**.  
3. Пройти циклом по **sort[101]** и посчитать сколько элементов **nums** строго меньше **sort[nums[i]]**. 
4. Записать полученные числа в новый вектор-ответ и вывести его на экран.

**Результат:** Данное решение было выполнено за 12 мс и задействовало 8 МБ памяти. Время выполнения оказалось быстрее, чем у 92,77% всех принятых решений других участников.

Насколько я могу судить, время выполнения вторым методом оказалось быстрее из-за выбора более оптимального алгоритма сортировки. Его применение целесообразно тогда, когда диапазон возможных значений массива мал по сравнению с размером самого массива.

2020-03-11 12:37 UTC, vitkarpov requested changes
Молодец, что сделал несколько решений. Нужно ещё оценить сложности и про сортировку счётчиками написал большой комментарий.

2020-03-11 12:37 UTC, vitkarpov commented on Solution #1.cpp
> +			out.push_back(distance(sol.begin(), sol.lower_bound(nums[i])));
Было бы круто оценить сложность решения, можно прямо в комментариях в коде, в начале файлика.
В данном случае: `lower_bound` — это бинарный поиск, соответсвенно логарифм помноженный на `nums.size()`.

2020-03-11 12:37 UTC, vitkarpov commented on Solution #2.cpp
> +			}
Здесь сложность хорошая из-за сортировки счётчиками 👍 Но от этого внутреннего цикла можно избавиться (хотя он даёт константу и сложность не меняет, понимаешь почему?).

Подсказка как избавиться от этого цикла. Рассмотрим пример `8 3 2 2 1`.
`sort` (название, кстати, так себе — лучше `sorted`) будет выглядет так:

```
value: 0 0 2 1 0 0 0 0 1 0
index: 0 1 2 3 4 5 6 7 8 9
```

Как для каждой чиселки в массиве сказать сколько чисел меньше? Меньше — значит сколько чисел слева. Можно за один проход преобразовать к следующему виду:

```
value: 0 0 2 3 3 3 3 3 4 0
index: 0 1 2 3 4 5 6 7 8 9
```
Соответственно, получился поисковый индекс по которому можно за O(1) сказать «а сколько чисел меньше 8?» — смотрим что лежит по восьмому индексу.

2020-03-11 19:33 UTC, Phillie19 commented
Оценку сложности я начал давать, но потом понял,что ничего об этом не
знаю,чтобы судить. полистал пару статей и пока забил, потому что писал бы
три строки два часа. А вот это

value: 0 0 2 3 3 3 3 3 4 0
index: 0 1 2 3 4 5 6 7 8 9

я не очень понял. Но под вечер переделал свой код на другой, по
времени ничего не изменилось.


ср, 11 мар. 2020 г. в 15:38, Viktor Karpov <notifications@github.com>:

> *@vitkarpov* requested changes on this pull request.
>
> Молодец, что сделал несколько решений. Нужно ещё оценить сложности и про
> сортировку счётчиками написал большой комментарий.
> ------------------------------
>
> In Solution #1.cpp
> <https://github.com/Phillie19/Tasks/pull/2#discussion_r390936165>:
>
> > @@ -0,0 +1,14 @@
> +class Solution {
> +public:
> +	vector<int> smallerNumbersThanCurrent(vector<int>& nums) {
> +		multiset <int> sol;
> +		vector <int> out;
> +		for (int i = 0; i < nums.size(); i++) {
> +			sol.insert(nums[i]);
> +		}
> +		for (int i = 0; i < nums.size(); i++) {
> +			out.push_back(distance(sol.begin(), sol.lower_bound(nums[i])));
>
> Было бы круто оценить сложность решения, можно прямо в комментариях в
> коде, в начале файлика.
> В данном случае: lower_bound — это бинарный поиск, соответсвенно логарифм
> помноженный на nums.size().
> ------------------------------
>
> In Solution #2.cpp
> <https://github.com/Phillie19/Tasks/pull/2#discussion_r390939977>:
>
> > @@ -0,0 +1,17 @@
> +class Solution {
> +public:
> +	vector<int> smallerNumbersThanCurrent(vector<int>& nums) {
> +		vector <int> sort(101);
> +		vector <int> output(nums.size());
> +
> +		for (int i = 0; i < nums.size(); i++) {
> +			sort[nums[i]] += 1;
> +		}
> +		for (int i = 0; i < nums.size(); i++) {
> +			for (int j = 0; j < nums[i]; j++) {
> +				output[i] += sort[j];
> +			}
>
> Здесь сложность хорошая из-за сортировки счётчиками 👍 Но от этого
> внутреннего цикла можно избавиться (хотя он даёт константу и сложность не
> меняет, понимаешь почему?).
>
> Подсказка как избавиться от этого цикла. Рассмотрим пример 8 3 2 2 1.
> sort (название, кстати, так себе — лучше sorted) будет выглядет так:
>
> value: 0 0 2 1 0 0 0 0 1 0
> index: 0 1 2 3 4 5 6 7 8 9
>
> Как для каждой чиселки в массиве сказать сколько чисел меньше? Меньше
> — значит сколько чисел слева. Можно за один проход преобразовать к
> следующему виду:
>
> value: 0 0 2 3 3 3 3 3 4 0
> index: 0 1 2 3 4 5 6 7 8 9
>
> Соответственно, получился поисковый индекс по которому можно за O(1)
> сказать «а сколько чисел меньше 8?» — смотрим что лежит по восьмому индексу.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Phillie19/Tasks/pull/2#pullrequestreview-372713204>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOWW4UHIN2ZWP42MVCI27YDRG6A3DANCNFSM4LFRPEMA>
> .
>

2020-03-11 19:35 UTC, Phillie19 commented
а нет. уже понял. я так потом и сделал.

ср, 11 мар. 2020 г. в 15:38, Viktor Karpov <notifications@github.com>:

> *@vitkarpov* requested changes on this pull request.
>
> Молодец, что сделал несколько решений. Нужно ещё оценить сложности и про
> сортировку счётчиками написал большой комментарий.
> ------------------------------
>
> In Solution #1.cpp
> <https://github.com/Phillie19/Tasks/pull/2#discussion_r390936165>:
>
> > @@ -0,0 +1,14 @@
> +class Solution {
> +public:
> +	vector<int> smallerNumbersThanCurrent(vector<int>& nums) {
> +		multiset <int> sol;
> +		vector <int> out;
> +		for (int i = 0; i < nums.size(); i++) {
> +			sol.insert(nums[i]);
> +		}
> +		for (int i = 0; i < nums.size(); i++) {
> +			out.push_back(distance(sol.begin(), sol.lower_bound(nums[i])));
>
> Было бы круто оценить сложность решения, можно прямо в комментариях в
> коде, в начале файлика.
> В данном случае: lower_bound — это бинарный поиск, соответсвенно логарифм
> помноженный на nums.size().
> ------------------------------
>
> In Solution #2.cpp
> <https://github.com/Phillie19/Tasks/pull/2#discussion_r390939977>:
>
> > @@ -0,0 +1,17 @@
> +class Solution {
> +public:
> +	vector<int> smallerNumbersThanCurrent(vector<int>& nums) {
> +		vector <int> sort(101);
> +		vector <int> output(nums.size());
> +
> +		for (int i = 0; i < nums.size(); i++) {
> +			sort[nums[i]] += 1;
> +		}
> +		for (int i = 0; i < nums.size(); i++) {
> +			for (int j = 0; j < nums[i]; j++) {
> +				output[i] += sort[j];
> +			}
>
> Здесь сложность хорошая из-за сортировки счётчиками 👍 Но от этого
> внутреннего цикла можно избавиться (хотя он даёт константу и сложность не
> меняет, понимаешь почему?).
>
> Подсказка как избавиться от этого цикла. Рассмотрим пример 8 3 2 2 1.
> sort (название, кстати, так себе — лучше sorted) будет выглядет так:
>
> value: 0 0 2 1 0 0 0 0 1 0
> index: 0 1 2 3 4 5 6 7 8 9
>
> Как для каждой чиселки в массиве сказать сколько чисел меньше? Меньше
> — значит сколько чисел слева. Можно за один проход преобразовать к
> следующему виду:
>
> value: 0 0 2 3 3 3 3 3 4 0
> index: 0 1 2 3 4 5 6 7 8 9
>
> Соответственно, получился поисковый индекс по которому можно за O(1)
> сказать «а сколько чисел меньше 8?» — смотрим что лежит по восьмому индексу.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Phillie19/Tasks/pull/2#pullrequestreview-372713204>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOWW4UHIN2ZWP42MVCI27YDRG6A3DANCNFSM4LFRPEMA>
> .
>

2020-03-11 19:38 UTC, Phillie19 commented
class Solution {
public:
    vector<int> smallerNumbersThanCurrent(vector<int>& nums) {
    vector <int> sorted(101);
    vector <int>:: iterator it;
vector <int> output;
for (it = nums.begin(); it != nums.end(); it++) {
sort[*it]++;
}
        vector <int> count(101);
        for (int i = 1; i < 101; i++) {
            count[i] = count[i-1] + sorted[i-1];
        }

for (it = nums.begin(); it != nums.end(); it++) {
output.push_back(count[*it]);
}
return output;
}
};

ср, 11 мар. 2020 г. в 22:35, Филипп Переверзев <philipps19@gmail.com>:

> а нет. уже понял. я так потом и сделал.
>
> ср, 11 мар. 2020 г. в 15:38, Viktor Karpov <notifications@github.com>:
>
>> *@vitkarpov* requested changes on this pull request.
>>
>> Молодец, что сделал несколько решений. Нужно ещё оценить сложности и про
>> сортировку счётчиками написал большой комментарий.
>> ------------------------------
>>
>> In Solution #1.cpp
>> <https://github.com/Phillie19/Tasks/pull/2#discussion_r390936165>:
>>
>> > @@ -0,0 +1,14 @@
>> +class Solution {
>> +public:
>> +	vector<int> smallerNumbersThanCurrent(vector<int>& nums) {
>> +		multiset <int> sol;
>> +		vector <int> out;
>> +		for (int i = 0; i < nums.size(); i++) {
>> +			sol.insert(nums[i]);
>> +		}
>> +		for (int i = 0; i < nums.size(); i++) {
>> +			out.push_back(distance(sol.begin(), sol.lower_bound(nums[i])));
>>
>> Было бы круто оценить сложность решения, можно прямо в комментариях в
>> коде, в начале файлика.
>> В данном случае: lower_bound — это бинарный поиск, соответсвенно
>> логарифм помноженный на nums.size().
>> ------------------------------
>>
>> In Solution #2.cpp
>> <https://github.com/Phillie19/Tasks/pull/2#discussion_r390939977>:
>>
>> > @@ -0,0 +1,17 @@
>> +class Solution {
>> +public:
>> +	vector<int> smallerNumbersThanCurrent(vector<int>& nums) {
>> +		vector <int> sort(101);
>> +		vector <int> output(nums.size());
>> +
>> +		for (int i = 0; i < nums.size(); i++) {
>> +			sort[nums[i]] += 1;
>> +		}
>> +		for (int i = 0; i < nums.size(); i++) {
>> +			for (int j = 0; j < nums[i]; j++) {
>> +				output[i] += sort[j];
>> +			}
>>
>> Здесь сложность хорошая из-за сортировки счётчиками 👍 Но от этого
>> внутреннего цикла можно избавиться (хотя он даёт константу и сложность не
>> меняет, понимаешь почему?).
>>
>> Подсказка как избавиться от этого цикла. Рассмотрим пример 8 3 2 2 1.
>> sort (название, кстати, так себе — лучше sorted) будет выглядет так:
>>
>> value: 0 0 2 1 0 0 0 0 1 0
>> index: 0 1 2 3 4 5 6 7 8 9
>>
>> Как для каждой чиселки в массиве сказать сколько чисел меньше? Меньше
>> — значит сколько чисел слева. Можно за один проход преобразовать к
>> следующему виду:
>>
>> value: 0 0 2 3 3 3 3 3 4 0
>> index: 0 1 2 3 4 5 6 7 8 9
>>
>> Соответственно, получился поисковый индекс по которому можно за O(1)
>> сказать «а сколько чисел меньше 8?» — смотрим что лежит по восьмому индексу.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Phillie19/Tasks/pull/2#pullrequestreview-372713204>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AOWW4UHIN2ZWP42MVCI27YDRG6A3DANCNFSM4LFRPEMA>
>> .
>>
>

2020-03-12 04:44 UTC, vitkarpov commented
@Phillie19 

Вместо вот этого:

```cpp
for (it = nums.begin(); it != nums.end(); it++) {
  sort[*it]++;
}
```

можно писать через range-based:

```cpp
for (auto v : nums) {
  sort[v]++;
}
```

Плюс, не очень понял зачем новый вектор `count`, а не менять тот же самый `sorted`.

**PS** Сделай, пожалуйста, ещё один коммит с новой версией твоего кода (взамен старого, в том же файле).

2020-03-12 07:52 UTC, vitkarpov commented on Solution #2.cpp
> +			}
**PS** Опечатка, по первому индексу не ноль, конечно, а один:

```
value: 0 1 2 1 0 0 0 0 1 0
index: 0 1 2 3 4 5 6 7 8 9
```

ну и результат вот такого прохода:

```cpp
for (int i = 1; i <= 100 ; i++) {
  sorted[i] += sorted[i - 1];
}
```

должен быть:

```
value: 0 1 3 4 4 4 4 4 5 0
index: 0 1 2 3 4 5 6 7 8 9
```

Чтобы ответить на вопрос «а сколько чисел меньше i-го» надо посмотреть в `i-1`

2020-03-12 08:13 UTC, vitkarpov commented on Solution #2.cpp
> +			}
**PPS**

Интерактивный пример как преобразовать за один проход — http://cpp.sh/9ib2d

2020-03-12 08:30 UTC, vitkarpov commented on Solution #2.cpp
> +	vector <int> output;
Что-то с отступами случилось, проверь, плз, что везде табы или пробелы единообразно.

2020-03-12 08:32 UTC, merged

2020-03-12 08:32 UTC, vitkarpov reviewed
Рано смерджил, я ещё не нажал approve 😞

2020-03-12 08:32 UTC, vitkarpov commented on Solution #2.cpp
> +    vector <int>:: iterator it;
А зачем этот итератор? 🤔

2020-03-12 08:32 UTC, vitkarpov commented on Solution #2.cpp
> +           	output.push_back(sorted[a-1]);
Проверь, плз, на тест `8 2 2 1 0` (с нулём).

2020-03-12 08:37 UTC, Phillie19 commented on Solution #2.cpp
> +    vector <int>:: iterator it;
а ни за чем. он остался с прошлого решения

2020-03-12 08:39 UTC, Phillie19 commented on Solution #2.cpp
> +           	output.push_back(sorted[a-1]);
С нулем не работает. буду разбираться